### ISSUE TITLE
Make the landing page responsive 

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/project-orsi#2]
### When the screen size is made smaller overflow in the x-axis starts. The expected behavior will be the Heading and the content will start getting smaller and the robot SVG is placed below the content and the blue gradient and white border SVG also remains in similar proportion in the mobile view. 
![orsi-ui](https://user-images.githubusercontent.com/67703407/115855077-7efc5a00-a448-11eb-9e71-aa0b3e30a5f8.png)

Attach the screenshot of the changes you make😃

**Comment by fantasy-08** [comment]
I can help

**Comment by Aniket762** [comment]
That will be great @fantasy-08

**Comment by Aniket762** [comment]
@fantasy-08  In the tablet and desktop view it looks great but in the mobile view it's looking a bit clumsy. It will be great if you can make the background where the robot is placed white and keep the blue gradient just at the right half of the screen. Let me know if I am clear.

![or1212](https://user-images.githubusercontent.com/67703407/115872716-bde9da00-a45f-11eb-9772-be93dac05433.png)

Looking forward to the amazing changes which you will make 😃

**Comment by Aniket762** [comment]
![or1212](https://user-images.githubusercontent.com/67703407/115872805-dbb73f00-a45f-11eb-8c9c-f11ceeb42358.png)

@fantasy-08 if this makes it more clear check it out
