### ISSUE TITLE
Contact Page Cards

### ISSUE THREAD

**Issue by sumana2001** [betaoverflow/project-orsi#5]
![image](https://user-images.githubusercontent.com/63084088/115954776-72433900-a510-11eb-9271-5573722d96a0.png)
Add contact cards similar to this below the got a query section in the contact page. Make sure the cards are responsive.
It'll be great if it has similar shadow effect or you can add something else of your own as well.
Please add a screenshot with the pull request.

**Comment by MIPB** [comment]
Hello, do you have the images for the cards?

**Comment by Wolfgang-stack** [comment]
Would love to work on this - feel free to assign me if you have time; otherwise, I will start working on it anyway

**Comment by Aniket762** [comment]
Hey @Wolfgang-stack go for it
